"Filed out from Dolphin Smalltalk 7"!

CMathLibrary subclass: #ArrayLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ArrayLibrary guid: (GUID fromString: '{02F6E2FD-9EA4-46FE-A025-5D64C4CD6056}')!
ArrayLibrary comment: ''!
!ArrayLibrary categoriesForClass!Unclassified! !
!ArrayLibrary class methodsFor!

fileName
	"Answer the host system file name for the library"

	^'SMALLAPACKARRAY'! !
!ArrayLibrary class categoriesFor: #fileName!public! !

