"Filed out from Dolphin Smalltalk 7"!

ArrayLibrary subclass: #ArrayDLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ArrayDLibrary guid: (GUID fromString: '{D7187478-D034-4C30-8E1A-A3B4B6BF1736}')!
ArrayDLibrary comment: ''!
!ArrayDLibrary categoriesForClass!Unclassified! !
!ArrayDLibrary methodsFor!

arraydtosWithn: n source: source result: result 
	<cdecl: void 'array_dtos'  SDWORD double * float * >
	^self invalidCall! !
!ArrayDLibrary categoriesFor: #arraydtosWithn:source:result:!public! !

